# Regresión Líneal Múltiple

In [7]:
import warnings
warnings.filterwarnings("ignore")

https://scikit-learn.org/stable/install.html

In [8]:
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
boston = datasets.load_boston()

In [10]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [11]:
print('Nombre de columnas:')
print(boston.feature_names)

Nombre de columnas:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [12]:
print("Informacion en el dataset:")
print(boston.keys())

Informacion en el dataset:
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])


In [13]:
print("Características del dataset:")
print(boston.DESCR)

Características del dataset:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per 

In [14]:
print("Cantidad de datos:")
print(boston.data.shape)

Cantidad de datos:
(506, 13)


In [18]:
# Seleccionamos como valor de la X las columnas desde la 5 a la 7:
X = boston.data[:, 5:8]
X

array([[ 6.575 , 65.2   ,  4.09  ],
       [ 6.421 , 78.9   ,  4.9671],
       [ 7.185 , 61.1   ,  4.9671],
       ...,
       [ 6.976 , 91.    ,  2.1675],
       [ 6.794 , 89.3   ,  2.3889],
       [ 6.03  , 80.8   ,  2.505 ]])

In [19]:
y = boston.target
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [17]:
from sklearn.model_selection import train_test_split
# Separo los datos de "train" entrenamiento y "test" prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [12]:
lr_multiple = linear_model.LinearRegression()

In [13]:
lr_multiple.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = lr_multiple.predict(X_test)
y_pred

array([18.79276177, 17.73510979, 20.73465914, 21.37471473, 17.21898942,
       38.38859727, 16.76781023, 24.40579856, 20.45987466, 24.01628751,
       32.3297146 , 19.11377292, 17.50903197, 20.84164342, 29.05698257,
       22.55099439, 31.11051505, 21.71249294, 19.46917556, 20.42829272,
       25.57548732, 15.86806046, 19.80033343, 19.43223127, 24.3501102 ,
       25.40571857, 17.74326318, 32.65336048, 19.06503057, 15.09986404,
       28.46292287, 29.02600038, 20.09174763, 41.65820573, 22.61442837,
       39.98314829, 19.7952586 ,  5.55018949, 24.42550662, 32.16807317,
        2.91434848, 35.58869343, 20.94325245, 20.07918567, 24.69006685,
       21.71028076, 27.33523576, 28.98083341, 30.75396422, 16.25476135,
       17.22293991, 25.49517977, 18.28590099, 25.99193838, 16.95861304,
       21.68507768, 10.34557923, 17.9511342 , 21.80700655, 22.01267441,
       16.51607471, 23.34276455, 13.43404191, 19.520875  , 15.26063662,
       23.70909006, 24.22197905, 29.29017538, 19.69122636, 23.48

In [15]:
y_test

array([19.3, 18.8, 19.9, 16.7, 17.4, 44.8, 15.6, 23.9, 22.6, 23.2, 32.2,
       18.2, 14.5, 23.3, 26.6, 24.6, 31.7, 13.1, 19.2, 19.4, 24.8, 16.2,
       20. , 20.3, 21.2, 22.9, 18.9, 33.2, 20.5, 12.7, 24.1, 29.1, 20.1,
       50. , 32.5, 50. , 20. ,  8.8, 16.4, 33.2, 13.8, 35.2,  7.2, 50. ,
       13.4, 11. , 28.2, 36. , 28.5, 20.8, 10.5, 27.1, 14.8, 23.7, 19.5,
       24. ,  9.7, 13.6, 20. , 20.3, 19.4, 15.2, 13.8, 17.8, 15.7, 24.7,
       22.6, 17.8, 22.9, 20.8,  8.4, 14.6, 13.5, 15.2, 11.7, 30.1, 16.3,
       22.6, 24.4, 17.1, 23.8, 22.2, 25. , 50. , 13.1, 21.1, 22. , 15.6,
       27.5, 31.2, 20.6, 18.2, 19.5, 19.3, 12.8, 30.8, 23.8,  7.4, 20.1,
       48.5, 23. , 21.7])

In [16]:
print('DATOS DEL MODELO REGRESIÓN LINEAL MULTIPLE')
print()
print('Valor de las pendientes o coeficientes "a":')
print(lr_multiple.coef_)
print('Valor de la intersección o coeficiente "b":')
print(lr_multiple.intercept_)

DATOS DEL MODELO REGRESIÓN LINEAL MULTIPLE

Valor de las pendientes o coeficientes "a":
[ 8.26735829 -0.09922621 -0.45898204]
Valor de la intersección o coeficiente "b":
-20.851496244318728


In [17]:
print("Precisión del modelo:")
print(lr_multiple.score(X_train, y_train))

Precisión del modelo:
0.5180381217359173
