# Random Forest Regression

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
# pip install scikit-learn

In [3]:
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
boston = datasets.load_boston()

In [5]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
print('Nombre de columnas:')
print(boston.feature_names)

Nombre de columnas:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [7]:
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [8]:
print("Informacion en el dataset:")
print(boston.keys())

Informacion en el dataset:
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])


In [9]:
print("Características del dataset:")
print(boston.DESCR)

Características del dataset:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per 

In [10]:
print("Cantidad de datos:")
print(boston.data.shape)

Cantidad de datos:
(506, 13)


In [11]:
# Seleccionamos como valor de la X la columna 6 (RM):
X = boston.data

In [12]:
y = boston.target

In [13]:
from sklearn.model_selection import train_test_split
# Separo los datos de "train" entrenamiento y "test" prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [14]:
from sklearn.ensemble import RandomForestRegressor
bar = RandomForestRegressor(n_estimators=300, max_depth=8)

In [15]:
bar.fit(X_train, y_train)

RandomForestRegressor(max_depth=8, n_estimators=300)

In [16]:
y_pred = bar.predict(X_test)
y_pred

array([18.85093827, 20.07142471, 14.77531983, 18.75163969, 42.17455516,
       27.76960534, 41.05244841, 20.19830906, 26.16258999, 23.48108088,
       41.12199935, 20.64094461, 40.73119206, 15.32805005, 27.10323032,
       23.58227279, 30.38008414, 12.73031568, 10.74439226,  8.9034552 ,
       19.23193765, 21.11063088, 31.09903812, 20.37047333,  8.84714816,
       23.7294051 , 20.59586479, 14.84378884, 12.78560953, 20.81610134,
       26.0000392 , 21.97709112, 15.29089201, 20.15090264, 11.64564146,
       14.8830455 , 25.8740306 , 47.78641111, 26.59066594, 14.12032481,
       25.77570982, 15.19621711, 17.87810353, 19.4736993 , 20.445585  ,
       43.75744465, 14.69022078, 15.17279588, 16.95725525, 20.80066529,
       19.35105814, 20.62797966, 20.42120339, 23.32119682, 20.85890826,
       30.7054814 , 28.59568895, 20.2965886 , 20.0256924 , 22.6438087 ,
       44.58870988, 11.20304139, 12.51241883, 27.08908764, 43.25840268,
       23.4554132 , 33.42434223, 28.36044624, 22.15650174, 33.53

In [17]:
y_test

array([20.5, 17.5, 15.4, 20.1, 43.8, 23.7, 50. , 18.6, 28.4, 22.3, 43.1,
       19.9, 50. , 14.1, 24. , 23.2, 31.2, 17.9, 12.1,  5.6, 16.8, 20.4,
       37. , 18.2,  7.4, 22.1, 18.4, 13. , 11.9, 21.7, 25. , 18.5, 13.1,
       22.4, 12.8, 13.6, 26.6, 48.5, 29. , 13.1, 26.5, 13.4, 20. , 15. ,
       20.8, 46. , 16.7, 14.9,  8.4, 21.7, 17.1, 24.3, 22.7, 24.5, 18.2,
       32.4, 29.1, 19.3, 22.9, 22.8, 44.8,  9.7,  7.5, 28. , 50. , 22.2,
       35.4, 26.6, 22.2, 36.1, 33.2, 42.3, 15. , 16.5, 22. , 29.9, 25. ,
       50. , 10.9, 14.4, 43.5, 31. , 20.6, 22.2, 21.1, 25.3, 22.5, 10.4,
       27.5, 50. , 24.6, 15.6, 20.3, 30.7, 21. , 10.5, 17.3, 14.3, 17.2,
       19.4, 13.1, 29.8])

In [18]:
print("Datos del modelo Bosques Aleatorios Regresión")
print()
print("precisión del modelo:")
print(bar.score(X_train, y_train))

Datos del modelo Bosques Aleatorios Regresión

precisión del modelo:
0.9682340177893398
